version: "3.7"
services:
  mongo:
    image: lnlscon/mailpy-db:v1.2
 #   image: mongo:4.4.1
    ports:
      - 27017:27017

  mail:
    image: lnlscon/mailpy-mail:v2.1
    build: .
    network_mode: host
    secrets:
      - ALERT_MAIL_PASSWORD
      - ALERT_MAIL_LOGIN
    environment:
      - ALERT_MAIL_PASSWORD=SIRIUS-2020
      - ALERT_MAIL_LOGIN=sirius.software.alert@gmail.com
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

secrets:
  ALERT_MAIL_PASSWORD:
    external: true
  ALERT_MAIL_LOGIN:
    external: true
