version: "3.7"
services:
  mongo:
    image: mongo:4.4.1
    ports:
      - 27017:27017

  sms:
    image: lnlscon/notification:v2.0
    build: .
    network_mode: host
    secrets:
      - ALERT_MAIL_PASSWORD
      - ALERT_MAIL_LOGIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

secrets:
  ALERT_MAIL_PASSWORD:
    external: true
  ALERT_MAIL_LOGIN:
    external: true
