version: "3.7"
services:
  db:
    container_name: mailpy-test-db
    image: mongo:4.4.3-bionic
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mailpy
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_USERNAME: test
      MONGO_INITDB_PASSWORD: test
    volumes:
      - ./00-create-db-users.sh:/docker-entrypoint-initdb.d/00-create-db-users.sh:ro
      - ./01-create-collections.js:/docker-entrypoint-initdb.d/01-create-collections.js:ro
      - ./02-insert-data.sh:/docker-entrypoint-initdb.d/02-insert-data.sh:ro
      - ./mailpy-db-2021-11-29:/mailpy-db-init-data:ro
